PET_WIDTH = 50
PET_HEIGHT = 50
PET_MOVIE_PATH = "Assets/pet.gif"

CHAT_WIN_OFFSET_X = -125
CHAT_WIN_OFFSET_Y = -370

MOVEMENT_X_MIN_RATIO = 0.40
MOVEMENT_X_MAX_RATIO = 0.60
MOVEMENT_Y_MIN_RATIO = 0.80
MOVEMENT_Y_MAX_RATIO = 0.95
